package com.example.minlishapp.core.utils

object LanguageHelper {
    private val translations = mapOf(
        // Navigation & Bottom Bar
        "Lộ trình" to "Roadmap",
        "Từ vựng" to "Vocabulary",
        "Thống kê" to "Statistics",
        "Cá nhân" to "Profile",

        // Dashboard Screen
        "Lộ trình học" to "Learning Roadmap",
        "Học từ mới" to "Learn New Words",
        "Đang tải..." to "Loading...",
        "Bắt đầu học" to "Start Learning",
        "Hồ sơ" to "Profile",
        "Bảng xếp hạng" to "Leaderboard",
        "Thống kê" to "Statistics",
        "Học viên Cấp độ" to "Learner Level",
        "Mục tiêu hàng ngày" to "Daily Target",
        "đã hoàn thành" to "completed",
        "XP tích lũy" to "Total XP",
        "Bài học hôm nay" to "Today's Lesson",
        "Bắt đầu ôn tập" to "Start Reviewing",
        "Chúc mừng bạn đã hoàn thành bài học!" to "Congratulations on completing your lesson!",
        "Chuỗi ngày" to "Day Streak",
        "Chính xác" to "Accuracy",
        "từ" to "words",
        "Vào học" to "Learn",
        
        // Vocab Decks Screen
        "Bộ từ vựng" to "Vocabulary Decks",
        "Tìm kiếm bộ từ..." to "Search decks...",
        "Tất cả" to "All",
        "Đang học" to "Learning",
        "Đã thuộc" to "Mastered",
        "Từ mới" to "New",
        "Đang ôn" to "Reviewing",
        "Nhập bộ từ" to "Import Deck",
        "Xuất bộ từ" to "Export Deck",
        "Tạo bộ từ mới" to "Create New Deck",
        "Tên bộ từ" to "Deck Name",
        "Chủ đề" to "Tag",
        "Không tìm thấy bộ từ vựng nào." to "No vocabulary decks found.",
        "Không tìm thấy kết quả cho" to "No results for",
        "+ Từ mới" to "+ Word",
        "Quản lý từ vựng" to "Manage Vocab",
        "Sửa thông tin" to "Edit Details",
        "Xóa bộ từ" to "Delete Deck",
        "Đã xóa" to "Deleted",
        "Tạo Bộ Từ Vựng Mới" to "Create New Deck",
        "Mô tả" to "Description",
        "Nhãn / Tags (Phân cách bằng dấu phẩy)" to "Tags (Comma separated)",
        "Ví dụ: IELTS, Giao tiếp" to "Example: IELTS, Communication",
        "Thêm bộ từ thành công" to "Deck added successfully",
        "Thêm Từ Vựng Vào Bộ" to "Add Words to Deck",
        "Bộ từ:" to "Deck:",
        "Từ tiếng Anh (*)" to "English Word (*)",
        "Loại từ:" to "Word Type:",
        "Động từ" to "Verb",
        "Danh từ" to "Noun",
        "Tính từ" to "Adjective",
        "Trạng từ" to "Adverb",
        "Phiên âm UK (*)" to "UK Pronunciation (*)",
        "Ví dụ: /ə'kɒmədeɪt/" to "Example: /ə'kɒmədeɪt/",
        "Nghĩa tiếng Việt (*)" to "Vietnamese Meaning (*)",
        "Câu ví dụ tiếng Anh" to "English Example Sentence",
        "Dịch nghĩa câu ví dụ" to "Example Translation",
        "Collocations (Phân cách bằng dấu phẩy)" to "Collocations (Comma separated)",
        "Ví dụ: accommodate guests, accommodate needs" to "Example: accommodate guests, accommodate needs",
        "Từ đồng nghĩa (Phân cách bằng dấu phẩy)" to "Synonyms (Comma separated)",
        "Ví dụ: hold, contain" to "Example: hold, contain",
        "Hủy" to "Cancel",
        "Thêm từ thành công" to "Word added successfully",
        "Vui lòng điền đủ các trường bắt buộc (*)" to "Please fill in all required fields (*)",
        "Lưu" to "Save",
        "Bộ từ này chưa có từ vựng nào." to "This deck has no words yet.",
        "Sửa từ vựng" to "Edit Word",
        "Từ vựng *" to "Word *",
        "Phiên âm" to "Pronunciation",
        "Nghĩa tiếng Việt *" to "Vietnamese Meaning *",
        "Nghĩa tiếng Anh" to "English Meaning",
        "Ví dụ" to "Example",
        "Cập nhật thành công" to "Updated successfully",
        "Vui lòng nhập đủ các trường bắt buộc" to "Please fill in all required fields",
        "Sửa Bộ Từ Vựng" to "Edit Deck",
        "Nhãn / Tags" to "Tags",
        "Đã sửa" to "Updated successfully",
        "Lỗi" to "Error",
        "Chọn Bộ Từ Xuất Ra" to "Select Deck to Export",
        
        // Profile Screen
        "Hồ Sơ" to "Profile",
        "Cài đặt học tập" to "Study Settings",
        "Chế độ giao diện Tối" to "Dark Mode",
        "Thay đổi mục tiêu học" to "Change Learning Goal",
        "Đặt lại toàn bộ tiến độ" to "Reset All Progress",
        "Thông báo học tập" to "Study Notifications",
        "Nhắc nhở học hàng ngày" to "Daily Reminders",
        "Nhận thông báo để duy trì chuỗi học tập" to "Get notified to maintain your streak",
        "Giờ nhắc học hàng ngày" to "Daily reminder time",
        "Ôn tập theo thuật toán SM-2" to "Spaced Repetition (SM-2)",
        "Nhắc ôn các từ đến hạn (Spaced Repetition)" to "Remind review cards on due dates",
        "Đăng xuất tài khoản" to "Logout Account",
        "Số từ học mỗi ngày" to "Daily Word Target",
        "từ / ngày" to "words / day",
        "Ngôn ngữ hiển thị" to "Display Language",
        "Chọn ngôn ngữ hiển thị" to "Select Display Language",
        "Đã đổi ngôn ngữ hiển thị thành công!" to "Display language updated successfully!",
        "Đã cập nhật mục tiêu học!" to "Learning goal updated successfully!",
        "Cập nhật thất bại!" to "Update failed!",
        "Đóng" to "Close",
        "Cài Đặt Giờ Nhắc Học" to "Set Reminder Time",
        "Chọn khung giờ nhắc học phù hợp:" to "Choose a suitable reminder time:",
        "Đặt lại tiến độ?" to "Reset progress?",
        "Toàn bộ tiến độ học tập, lịch sử ôn tập và điểm XP tích lũy sẽ bị xóa vĩnh viễn trên cơ sở dữ liệu. Bạn có chắc chắn muốn thực hiện?" to "All learning progress, review history, and accumulated XP will be permanently deleted from the database. Are you sure you want to proceed?",
        "Xác nhận xóa" to "Confirm delete",
        "Đã khôi phục cài đặt tiến độ ban đầu thành công!" to "Learning progress has been reset successfully!",
        "Đặt lại tiến độ thất bại!" to "Failed to reset progress!",
        "Đăng xuất thành công!" to "Logout successful!",
        "Đã đổi tên thành công!" to "Name updated successfully!",
        "Đổi tên thất bại!" to "Failed to update name!",
        "Lỗi kết nối" to "Connection error",
        "Tùy chỉnh chọn giờ ⚙️" to "Custom Time ⚙️",
        "Giao tiếp" to "Communication",
        "THPT Quốc gia" to "High School Exam",
        
        // Welcome & Login Screen
        "Chào mừng tới MinLish" to "Welcome to MinLish",
        "Phương pháp Spaced Repetition (SM-2) kết hợp trò chơi hóa giúp bạn học từ vựng tiếng Anh không bao giờ quên." to "The Spaced Repetition (SM-2) method combined with gamification helps you learn English vocabulary and never forget it.",
        "Đăng nhập" to "Login",
        "Chào mừng trở lại!" to "Welcome back!",
        "Tạo tài khoản mới" to "Create new account",
        "Đăng nhập để tiếp tục lộ trình học" to "Login to continue your learning roadmap",
        "Đăng ký nhanh chóng chỉ với vài bước" to "Register quickly in just a few steps",
        "Đăng ký" to "Register",
        "Địa chỉ Email" to "Email Address",
        "Mật khẩu" to "Password",
        "Xác nhận mật khẩu" to "Confirm Password",
        "Quên mật khẩu?" to "Forgot password?",
        "Vui lòng nhập đầy đủ thông tin!" to "Please fill in all information!",
        "Địa chỉ email không hợp lệ!" to "Invalid email address!",
        "Mật khẩu phải chứa ít nhất 6 ký tự!" to "Password must contain at least 6 characters!",
        "Mật khẩu xác nhận không khớp!" to "Confirm password does not match!",
        "Đăng nhập thất bại!" to "Login failed!",
        "Đăng ký thất bại!" to "Registration failed!",
        "hoặc" to "or",
        "Đăng nhập với Google" to "Login with Google",
        "Khôi phục mật khẩu" to "Restore Password",
        "Nhập địa chỉ email của bạn. Chúng tôi sẽ gửi một liên kết đổi mật khẩu mới." to "Enter your email address. We will send a password reset link.",
        "Email khôi phục" to "Recovery Email",
        "Đã gửi liên kết khôi phục tới email của bạn!" to "Recovery link sent to your email!",
        "Gửi email khôi phục thất bại!" to "Failed to send recovery email!",
        "Email không hợp lệ!" to "Invalid email!",
        "Gửi liên kết" to "Send Link",
        "Đăng nhập Google thất bại!" to "Google login failed!",
        "Đăng nhập Google bị hủy hoặc thất bại." to "Google login was cancelled or failed.",
        "Có lỗi xảy ra, vui lòng thử lại sau." to "An error occurred, please try again later.",
        "Email hoặc mật khẩu không chính xác!" to "Incorrect email or password!",
        "Địa chỉ email chưa được xác nhận!" to "Email address not confirmed!",
        "Tài khoản email này đã được sử dụng!" to "This email account is already in use!",
        "Mật khẩu quá yếu! Yêu cầu ít nhất 6 ký tự." to "Password is too weak! At least 6 characters required.",
        
        // Reset Password Screen
        "Đặt lại mật khẩu mới" to "Reset new password",
        "Nhập mật khẩu mới của bạn bên dưới để khôi phục quyền truy cập vào tài khoản." to "Enter your new password below to restore access to your account.",
        "Mật khẩu mới" to "New password",
        "Xác nhận mật khẩu mới" to "Confirm new password",
        "Vui lòng điền đầy đủ mật khẩu!" to "Please fill in all passwords!",
        "Đổi mật khẩu thành công! Vui lòng đăng nhập lại." to "Password changed successfully! Please login again.",
        "Đổi mật khẩu thất bại!" to "Failed to reset password!",
        "Cập nhật mật khẩu" to "Update Password",
        "Quay lại đăng nhập" to "Back to Login",
        
        // Stats Screen
        "Thống Kê" to "Statistics",
        "Tổng từ đã học" to "Total studied words",
        "Streak hiện tại" to "Current streak",
        "Tỷ lệ nhớ lâu" to "Retention rate",
        "Số từ ôn tập hằng ngày" to "Daily reviewed words",
        "Tỷ lệ trạng thái từ vựng" to "Vocabulary status ratio",
        "Thành thạo" to "Proficient",
        "Đang nhớ" to "Learning",
        "Cần ôn gấp" to "Needs review",
        "Thử lại" to "Retry",
        "ngày" to "days",
        
        // Lesson Complete Screen
        "Hoàn Thành Bài Học!" to "Lesson Completed!",
        "Bạn đã hoàn thành xuất sắc mục tiêu ngày hôm nay. Hãy duy trì phong độ nhé!" to "You completed today's target successfully. Keep it up!",
        "Kinh nghiệm" to "XP Gained",
        "Tiếp tục lộ trình" to "Continue Roadmap",
        
        // Flashcard Screen
        "Lật Thẻ" to "Flip Card",
        "Học tiếp" to "Learn More",
        "Đã thuộc (Đánh giá SM-2)" to "Mastered (SM-2 Rating)",
        "Nhấn để xem nghĩa" to "Tap to reveal meaning",
        "Cụm từ đi kèm (Collocations)" to "Collocations",
        "Đồng nghĩa:" to "Synonyms:",
        "Gợi ý: Từ bắt đầu bằng chữ" to "Hint: Word starts with letter",
        "Kiểm tra" to "Check",
        "Đánh giá mức độ dễ nhớ của từ:" to "Rate how easy it is to remember the word:",
        "Học lại (<1m)" to "Again (<1m)",
        "Khó (10m)" to "Hard (10m)",
        "Tốt (1d)" to "Good (1d)",
        "Dễ (4d)" to "Easy (4d)",
        "Gõ từ tiếng Anh..." to "Type the English word...",
        "Gợi ý: Từ bắt đầu bằng" to "Hint: Word starts with",
        "và có" to "and has",
        "chữ cái." to "letters.",
        "Đáp án đúng:" to "Correct answer:",
        "Bấm 1, 2, 3, 4 trên bàn phím hoặc chạm đáp án để chọn" to "Press 1, 2, 3, 4 on keyboard or tap option to choose",
        "Bấm Enter để kiểm tra nhanh kết quả" to "Press Enter to quickly check result",
        "Đánh giá khả năng nhớ từ của bạn" to "Evaluate your retention of the word",
        "Đã học" to "Learned",
        "Ôn tập" to "Review",
        "Gợi ý: Nhấn 'Đã thuộc' hoặc 'Học tiếp' để bắt đầu luyện tập" to "Hint: Tap 'Mastered' or 'Learn More' to start practicing"
    )

    fun translate(text: String, appLanguage: String): String {
        if (appLanguage != "English") return text
        
        val translated = translations[text]
        if (translated != null) return translated
        
        var temp = text
        for ((vi, en) in translations) {
            if (temp.contains(vi)) {
                temp = temp.replace(vi, en)
            }
        }
        return temp
    }
}

fun String.translated(appLanguage: String): String {
    return LanguageHelper.translate(this, appLanguage)
}

